name: Rush Hour Build
run-name: ${{ github.actor }} is testing out Rush Hour Build 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Compile with Maven
        run: cd rush-hour-solver && mvn clean compile

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Test with Maven
        run: cd rush-hour-solver && mvn clean test

  run:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Execute with Maven
        run: cd rush-hour-solver && mvn clean compile exec:java

      - name: Archive graphs
        uses: actions/upload-artifact@v4
        with:
          name: graphs
          path: rush-hour-solver/target/*.png

  build-jar:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build JAR with Maven
        run: cd rush-hour-solver && mvn clean package

      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: shaded-jar
          path: |
            rush-hour-solver/target/*.jar
            !rush-hour-solver/target/original-*.jar
      