name: Rush Hour Build
run-name: ${{ github.actor }} is testing out Rush Hour Build 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Compile with Maven
        run: cd rush-hour-solver && mvn compile

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Test with Maven
        run: cd rush-hour-solver && mvn test

  run:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Execute with Maven
        run: cd rush-hour-solver && mvn exec:java

      - name: Archive graphs
        uses: actions/upload-artifact@v4
        with:
          name: graphs
          path: target/*.png
      