name: Rush Hour Build
run-name: ${{ github.actor }} is testing out Rush Hour Build 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Compile with Maven
        run: cd rush-hour-solver && mvn clean compile

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Test with Maven
        run: cd rush-hour-solver && mvn clean test

  run:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Execute with Maven
        run: cd rush-hour-solver && mvn clean compile exec:java

      - name: Archive graphs
        uses: actions/upload-artifact@v4
        with:
          name: graphs
          path: rush-hour-solver/target/*.png

  build-jar:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build JAR with Maven
        run: cd rush-hour-solver && mvn clean package

      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: shaded-jar
          path: rush-hour-solver/target/rush-hour-solver*.jar

  lint:
    needs: build-jar
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Verify package with Maven
        run: cd rush-hour-solver && mvn clean verify

      - name: Generate human-readable output
        run: cd rush-hour-solver && mvn site

      - name: Archive site html pages
        uses: actions/upload-artifact@v4
        with:
          name: site-html
          path: rush-hour-solver/target/site/*

  build-deb:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build deb package with Maven
        run: cd rush-hour-solver && mvn clean install

      - name: Archive deb package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: rush-hour-solver/target/rush-hour-solver*.deb

  lint-deb:
    needs: build-deb
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install lintian

      - name: Download deb package artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-package

      - name: Lint deb package
        run: lintian rush-hour-solver*.deb || true

  install-deb:
    needs: build-deb
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Download deb package artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: deb

      - name: Install deb package
        run: |
          sudo dpkg -i deb/*.deb
          sudo apt install -f -y  # fix dependencies if needed

      - name: Run installed program (short timeout)
        run: |
          set -e
          if timeout 5s rush-hour-solver; then
            echo "Program started and exited cleanly."
            exit 0
          else
            exit_code=$?
            if [ $exit_code -eq 124 ]; then
              echo "Program started successfully but timed out (expected)."
              exit 0
            else
              echo "Program failed to start correctly (exit code $exit_code)."
              exit $exit_code
            fi
          fi
      